### ISSUE TITLE
拉取最新的master，编译失败

### ISSUE THREAD

**Issue by tunsuy** [Huawei/openstack4j#25]
执行命令：mvn clean package install  -DskipTests -X

错误信息：  
```java
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.3:compile (default-compile) on project openstack4j-core: Compilation failure: Compilation failure:
[ERROR] /D:/validate-sdk/openstack4j/core/src/main/java/org/openstack4j/openstack/sahara/internal/ClusterServiceImpl2.java:[26,30] ▒▒▒▒▒org.testng.collections▒▒▒▒▒▒
[ERROR] /D:/validate-sdk/openstack4j/core/src/main/java/org/openstack4j/openstack/sahara/domain/SaharaClusterCreate.java:[26,37] ▒▒▒▒▒com.beust.jcommander.internal▒▒▒▒▒▒
[ERROR] -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.3:compile (default-compile) on project openstack4j-core: Compilation failure
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:213)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:154)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:146)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)

```

**Comment by IamFive** [comment]
稍等，估计是引错包了

**Comment by IamFive** [comment]
重新更新下。

**Comment by tunsuy** [comment]
还是不行，这次又报新的错了
```java
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 02:13 min
[INFO] Finished at: 2017-07-14T16:53:16+08:00
[INFO] Final Memory: 59M/788M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.3:compile (default-compile) on project openstack4j-sample: Compilation failure
[ERROR] /D:/validate-sdk/openstack4j/sample/src/main/java/org/openstack4j/sample/AbstractSample.java:[51,65] ▒Ҳ▒▒▒▒▒▒▒
[ERROR]   ▒▒▒▒:   ▒▒▒▒ KEY_MANAGEMENT
[ERROR]   λ▒▒: ▒▒ org.openstack4j.api.types.ServiceType
[ERROR]
[ERROR] -> [Help 1]

```

**Comment by IamFive** [comment]
汗。。把无关的代码给提交上去了。

**Comment by IamFive** [comment]
再试一下。
