### ISSUE TITLE
\core\src\main\java\org\openstack4j\openstack\maas\internal\TaskService.java line 134 Integer不能强转为String

### ISSUE THREAD

**Issue by Mageric0412** [Huawei/openstack4j#42]
\core\src\main\java\org\openstack4j\openstack\maas\internal\TaskService.java line 134

执行方法
public long count(State state) {
		checkArgument(state != null, "state is required");
		Map result = get(Map.class, uri("/task")).param("totalcount", true).param("state", state.getVal()).execute();
		if (result.containsKey("taskcount")) {
			return Long.parseLong((String) result.get("taskcount"));
		} else
			return 0;
	}

报错：
`FAILED: testTaskCountByState
java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.String
	at org.openstack4j.openstack.maas.internal.TaskService.count(TaskService.java:134)
	at org.openstack4j.sample.maas.MaaSSample.testTaskCountByState(MaaSSample.java:160)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:335)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:330)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)`

第134行`return Long.parseLong((String) result.get("taskcount"));`
**不能直接将Integer类型强转为String。**

要么使用`.longValue()`：
`if (result.containsKey("taskcount")) {
			Integer taskcount = (Integer) result.get("taskcount");
			return taskcount.longValue();
 }`

**Comment by biaocy** [comment]
你贴的不是最新代码，可能部署的不是最新版本？ [master](https://github.com/Huawei/openstack4j/blob/master/core/src/main/java/org/openstack4j/openstack/maas/internal/TaskService.java#L116)

**Comment by biaocy** [comment]
看错了，不好意思，稍等

**Comment by IamFive** [comment]
Fixed 更新代码。
