### ISSUE TITLE
VBSVolumeBackupPolicyBackupTask.java的问题

### ISSUE THREAD

**Issue by 42701618** [Huawei/openstack4j#6]
VBSVolumeBackupPolicyBackupTask.java里的49行FORMAT_YMDTHMS_SSS是不是么有

**Comment by IamFive** [comment]
你有更新代码吗，要全部更新下来，然后要重新 mvn clean package install -DskipTests

**Comment by 42701618** [comment]
Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.3:compile (default-compile) on project openstack4j-core: Compilation failure: Compilation failure:
[ERROR] /D:/openstack4j-master/core/src/main/java/org/openstack4j/openstack/storage/block/internal/VBSVolumeBackupPolicyService.java:[24,18] ▒▒▒▒▒org.testng▒▒▒▒▒▒
[ERROR] /D:/openstack4j-master/core/src/main/java/org/openstack4j/openstack/storage/block/internal/VBSVolumeBackupPolicyService.java:[25,30] ▒▒▒▒▒org.testng.collections▒▒▒▒▒▒
[ERROR] /D:/openstack4j-master/core/src/main/java/org/openstack4j/openstack/storage/block/internal/VBSVolumeBackupPolicyService.java:[26,23] ▒▒▒▒▒org.testng.util▒▒▒▒▒▒
[ERROR] -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.3:compile (default-compile) on project openstack4j-core: Compilation failure
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:862)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:286)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:197)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.compiler.CompilationFailureException: Compilation failure
        at org.apache.maven.plugin.compiler.AbstractCompilerMojo.execute(AbstractCompilerMojo.java:911)
        at org.apache.maven.plugin.compiler.CompilerMojo.execute(CompilerMojo.java:129)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
        ... 20 more
[ERROR]
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :openstack4j-core

**Comment by IamFive** [comment]
这个是在 core 里面引用了错误的包， 你稍等几分钟，包重新改一下

**Comment by IamFive** [comment]
重新更新下

**Comment by 42701618** [comment]
是master吗，试了两次，还是那样

**Comment by IamFive** [comment]
。。。。 又忘记push到 github了。。

**Comment by IamFive** [comment]
诶，我看了提交记录 有commit啊。
![image](https://user-images.githubusercontent.com/1578702/27783829-589be028-600a-11e7-9f77-7d02ed6db30b.png)

**Comment by 42701618** [comment]
[ERROR] /D:/openstack4j-master/core/src/main/                                                                                                                                                                                             java/org/openstack4j/openstack/storage/block/internal/CloudVolumeBackupServiceImpl                                                                                                                                                                                             .java:[45,97] ▒▒▒▒▒ݵ▒▒▒▒▒: org.openstack4j.openstack.storage.block.domain.VBSVolum                                                                                                                                                                                             eBackupJob▒޷▒ת▒▒Ϊorg.openstack4j.model.storage.block.CloudVolumeBackupJob
[ERROR] -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org                                                                                                                                                                                             .apache.maven.plugins:maven-compiler-plugin:3.3:compile (default-compile) on proje                                                                                                                                                                                             ct openstack4j-core: Compilation failure
/D:/openstack4j-master/core/src/main/java/org                                                                                                                                                                                             /openstack4j/openstack/storage/block/internal/CloudVolumeBackupServiceImpl.java:[4                                                                                                                                                                                             5,97] ▒▒▒▒▒ݵ▒▒▒▒▒: org.openstack4j.openstack.storage.block.domain.VBSVolumeBackupJ                                                                                                                                                                                             ob▒޷▒ת▒▒Ϊorg.openstack4j.model.storage.block.CloudVolumeBackupJob

        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.j                                                                                                                                                                                             ava:212)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.j                                                                                                                                                                                             ava:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.j                                                                                                                                                                                             ava:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject                                                                                                                                                                                             (LifecycleModuleBuilder.java:116)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject                                                                                                                                                                                             (LifecycleModuleBuilder.java:80)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThread                                                                                                                                                                                             edBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleS                                                                                                                                                                                             tarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:862)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:286)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:197)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.ja                                                                                                                                                                                             va:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccesso                                                                                                                                                                                             rImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launch                                                                                                                                                                                             er.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:                                                                                                                                                                                             229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Laun                                                                                                                                                                                             cher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:35                                                                                                                                                                                             6)
Caused by: org.apache.maven.plugin.compiler.CompilationFailureException: Compilati                                                                                                                                                                                             on failure
/D:/2016/ces/bushu/3.0.9/yan_java/intell/openstack4j-master/core/src/main/java/org                                                                                                                                                                                             /openstack4j/openstack/storage/block/internal/CloudVolumeBackupServiceImpl.java:[4                                                                                                                                                                                             5,97] ▒▒▒▒▒ݵ▒▒▒▒▒: org.openstack4j.openstack.storage.block.domain.VBSVolumeBackupJ                                                                                                                                                                                             ob▒޷▒ת▒▒Ϊorg.openstack4j.model.storage.block.CloudVolumeBackupJob

        at org.apache.maven.plugin.compiler.AbstractCompilerMojo.execute(AbstractC                                                                                                                                                                                             ompilerMojo.java:911)
        at org.apache.maven.plugin.compiler.CompilerMojo.execute(CompilerMojo.java                                                                                                                                                                                             :129)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBu                                                                                                                                                                                             ildPluginManager.java:134)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.j                                                                                                                                                                                             ava:208)
        ... 20 more
[ERROR]
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read                                                                                                                                                                                              the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureExcep                                                                                                                                                                                             tion
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :openstack4j-core

**Comment by IamFive** [comment]
这个是因为你本地修改过了代码，导致这个文件有冲突。其实这个文件已经被重命名过了，现在不叫 
`CloudVolumeBackupJob` ，现在的job-impl叫 `VBSVolumeBackupJobServiceImpl` 。

你如果本地修改过的代码是无关紧要的， 运行 git reset --hard 然后在 git pull。如果修改的代码是需要的，那你要自己 merge一下代码

**Comment by 42701618** [comment]
OK了
