### ISSUE TITLE
CloudEyeSample里测testGetMetrics的问题

### ISSUE THREAD

**Issue by 42701618** [Huawei/openstack4j#7]
CloudEyeSample里测testGetMetrics，把 options.namespace("SYS");或者 options.namespace("s");或者 options.namespace("");。
我看debug log是， "{"code":400,"element":"Bad Request","message":"The system received a request which cannot be recognized","details":{"details":"The URL parameter is invalid or does not exist.","code":"ces.0013"}}"

我觉得这个是对的，但是test case的结果报错

15:36:43.003 [main] DEBUG o.a.h.i.c.PoolingHttpClientConnectionManager - Connection [id: 1][route: {s}->https://*.*.*.*:*] can be kept alive indefinitely
15:36:43.003 [main] DEBUG o.a.h.i.c.PoolingHttpClientConnectionManager - Connection released: [id: 1][route: {s}->https://*.*.*.*:*:443][total kept alive: 2; route allocated: 1 of 2; total allocated: 2 of 20]

ClientResponseException{message=Status: 400, Reason: Bad Request
, status=400, status-code=BAD_REQUEST}
	at org.openstack4j.core.transport.HttpExceptionHandler.mapException(HttpExceptionHandler.java:53)
	at org.openstack4j.core.transport.HttpExceptionHandler.mapException(HttpExceptionHandler.java:38)
	at org.openstack4j.core.transport.HttpEntityHandler.handleLessThan500(HttpEntityHandler.java:116)
	at org.openstack4j.core.transport.HttpEntityHandler.handle(HttpEntityHandler.java:62)
	at org.openstack4j.connectors.httpclient.HttpResponseImpl.getEntity(HttpResponseImpl.java:82)
	at org.openstack4j.openstack.internal.BaseOpenStackService$Invocation.execute(BaseOpenStackService.java:242)
	at org.openstack4j.openstack.internal.BaseOpenStackService$Invocation.execute(BaseOpenStackService.java:224)
	at org.openstack4j.openstack.cloudeye.internal.CloudEyeMetricServiceImpl.getList(CloudEyeMetricServiceImpl.java:22)
	at org.openstack4j.sample.cloudeye.CloudEyeSample.testGetMetrics(CloudEyeSample.java:40)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:72)
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:127)

**Comment by IamFive** [comment]
整个是服务端返回的数据，客户端这边是服务端返回什么错误信息，就抛出什么异常。

**Comment by IamFive** [comment]
HTTP 返回数据的处理是公共的，都是在 HTTP transport 的封装包里面。对应的方法是：
`org.openstack4j.core.transport.HttpEntityHandler.handle(HttpResponse, Class<T>, ExecutionOptions<T>, boolean)`
